#!/bin/bash

cd /Users/xingl/Desktop/XLTest/OC_APP/OC_APP
myworkspace=OC_APP.xcworkspace # 替换workspace的名字
myscheme=OC_APP # 替换scheme的名字
xcodebuild -workspace $myworkspace -scheme $myscheme clean&&
xcodebuild -workspace $myworkspace -scheme $myscheme \
-configuration Debug \
| xcpretty -r json-compilation-database -o compile_commands.json

if [ -f ./compile_commands.json ]; then echo '-----编译数据生成完毕-----'
else echo "-----生成编译数据失败-----"; fi

#生成报表
oclint-json-compilation-database -e Pods -- \
-report-type html -o oclint_result.html \
-rc LONG_LINE=200 \
-max-priority-1=100000 \
-max-priority-2=100000 \
-max-priority-3=100000; \
rm compile_commands.json;
if [ -f ./oclint_result.html ]; then echo '-----分析完毕-----'
else echo "-----分析失败-----"; fi